version: "3.8"

services:
  api:
    build: .
    container_name: catalogo_cfstyle_api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
db:
  image: postgres:16
  environment:
    POSTGRES_DB: CFStyle
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: 1234
  ports:
    - "5432:5432"
